export const spacesData = [
  {
    id: 1,
    categories: ["Résidentiel", "Luxe"],
    image: "/spaces/space-1.jpg",
    date: "Prix sur demande",
    name: "Villa de Luxe",
    location: "Marrakech, Maroc",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "Rimal Immobilier",
    route: "/sample-space",
  },
  {
    id: 2,
    categories: ["Résidentiel", "Traditionnel"],
    image: "/spaces/space-2.jpg",
    date: "Prix sur demande",
    name: "Riad Traditionnel",
    location: "Fès, Maroc",
    clientImage: "/spaces/client-2.jpeg",
    clientName: "Rimal Immobilier",
    route: "/sample-space",
  },
  {
    id: 3,
    categories: ["Résidentiel", "Moderne"],
    image: "/spaces/space-3.jpg",
    date: "Prix sur demande",
    name: "Appartement Standing",
    location: "Casablanca, Maroc",
    clientImage: "/spaces/client-3.jpeg",
    clientName: "Rimal Immobilier",
    route: "/sample-space",
  },
  {
    id: 4,
    categories: ["Terrain", "Investissement"],
    image: "/spaces/space-4.jpg",
    date: "Prix sur demande",
    name: "Terrain Titré",
    location: "Tanger, Maroc",
    clientImage: "/spaces/client-4.jpeg",
    clientName: "Rimal Immobilier",
    route: "/sample-space",
  },
  {
    id: 5,
    categories: ["Commercial", "Investissement"],
    image: "/spaces/space-5.jpg",
    date: "Prix sur demande",
    name: "Local Commercial",
    location: "Rabat, Maroc",
    clientImage: "/spaces/client-5.jpeg",
    clientName: "Rimal Immobilier",
    route: "/sample-space",
  },
  {
    id: 6,
    categories: ["Résidentiel", "Moderne"],
    image: "/spaces/space-6.jpg",
    date: "Prix sur demande",
    name: "Duplex Moderne",
    location: "Agadir, Maroc",
    clientImage: "/spaces/client-6.jpeg",
    clientName: "Rimal Immobilier",
    route: "/sample-space",
  },
  {
    id: 7,
    categories: ["Résidentiel", "Luxe"],
    image: "/spaces/space-7.jpg",
    date: "Prix sur demande",
    name: "Penthouse",
    location: "Essaouira, Maroc",
    clientImage: "/spaces/client-7.jpeg",
    clientName: "Rimal Immobilier",
    route: "/sample-space",
  },
];
